### ISSUE TITLE
Doc -- Architecture and Design of Distributed Key Architecture

### ISSUE THREAD

**Issue by GerryG** [holochain/holochain-proto#149]
## Design Topics
**1. Encryption
2. Authenticity
3. Public Key Provenance
4. Private Key Security
5. Strength of Security Claims**

**Comment by GerryG** [comment]
I think the first task is actually to make this list better.

**Comment by artbrock** [comment]
I'm going to take this as a request to participate in a design discussion meeting. Let's have this discussion following the dev coord meeting on 5/9.

**Comment by GerryG** [comment]
I like that, this is next Tues?

**Comment by artbrock** [comment]
Yep. Dev coord is noon eastern for 30 minutes. Then dev docs call starts, but we can use it for documenting design of key mgt.

**Comment by GerryG** [comment]
Are there any starting docs or references we can build from? Maybe name a page at least?
