### ISSUE TITLE
Docker - Dockerfiles for Development

### ISSUE THREAD

**Issue by GerryG** [holochain/holochain-proto#150]
Support in container development.

This could be based on most golang registered images. The WIP is on wheezy and has ruby 22 also installed. We can make several Dockerfiles to support desired variations.

**Comment by GerryG** [comment]
This is a long living container with the active workspaces using symbolic links in $GOPATH directories to locations on the mounted workspace directory (/work2 in the WIP, could be anything). I will leave this ticket on the backlog unless someone else wants to use it. Add yourself to the ticket and ping me.

**Comment by christopherreay** [comment]
what's your vision for the functionality inside the container? 

particular development tools? or something more lightweight?

**Comment by timotree3** [comment]
#205 implements gets this started although people will still have to add their favorite development tools to it.
