### ISSUE TITLE
Complete the low level design for Holochain DHT Neighbourhood

### ISSUE THREAD

**Issue by christopherreay** [holochain/holochain-proto#320]
![fullboard 70pccontent](https://user-images.githubusercontent.com/239550/28996342-8f1dc64e-79b3-11e7-8e9c-a10fc0ae45ef.jpg)

* Design Document
  * https://docs.google.com/document/d/1_tLUFwQoS-JNppKbxpLdW57GktJ2bfScVTmapmFaX6I/edit
  * should that bea hack md

**Comment by christopherreay** [comment]
![img_20170804_122831](https://user-images.githubusercontent.com/239550/28996351-9be74f94-79b3-11e7-8e16-8aeba2cd06d1.jpg)
#### The different reasons for having neibourhoods
* Scaling (i.e. accesibility to smaller devices)
* Policing
  * neighbourhoods independently verify each piece of data in a relatively short space of time after publishing
  * This gives constant policing
  * Until sufficient members of a neighbourhood have verified a piece of data, that data is not available on the DHT / is marked as unverified
* Availability

**Comment by christopherreay** [comment]
![img_20170804_122831](https://user-images.githubusercontent.com/239550/28996351-9be74f94-79b3-11e7-8e16-8aeba2cd06d1.jpg)
#### The different reasons for having neibourhoods
* Scaling (i.e. accesibility to smaller devices)
* Policing
  * neighbourhoods independently verify each piece of data in a relatively short space of time after publishing
  * This gives constant policing
  * Until sufficient members of a neighbourhood have verified a piece of data, that data is not available on the DHT / is marked as unverified
* Availability

**Comment by christopherreay** [comment]
![all sel nodes](https://user-images.githubusercontent.com/239550/28996396-ac91d7a0-79b4-11e7-8321-509a346820ae.jpg)

#### Gossip Selection
* The larger bracket (ALL) is ALL the nodes this node knows about
* nXOR is the "redundancy/policing" number
* The smaller bracket (SEL) is the nXOR number of nodes that this node selects to be the closest to that some newly arrived piece of data
  * This is the “closest” by spherical XOR
  * oldest first sort
* If a receivingNode receives a message that some other node would like to enter into a gossip policing/availability strategy regarding a piece of data, if the receivingNode knows nXOR nodes closer to the data than itself, it replies with that list of peers, and hangs up.

**Comment by christopherreay** [comment]
![xxor agesorting](https://user-images.githubusercontent.com/239550/28996642-7ca6477e-79b9-11e7-99d0-068307ac1542.jpg)

* The smaller bracket (SEL) is the nXOR number of nodes that this node selects to be the closest to that some newly arrived piece of data
* This is the “closest” by spherical XOR
oldest first sort

**Comment by zippy** [comment]
@zippy I will do sprint to try out integration with IPFS

**Comment by christopherreay** [comment]
So as far as implementation details:
* the go-libp2p-kad-dht repository is already forked into metacurrency
* attempt to port the behaviour of the existing actions (e.g. PutRequest and Validate) into "handlers.go" and its surrounding protocols.
* Add a new module "holochain dht neighborhoods".go, to the package, and find out where it needs to cross cut with the existing implementation
  * it is possible that it will only need to be code in handlers.go plus some module of behaviour

Can people sign off that this is where we are headed?
- [ ] @zippy 
- [ ] @dayzee
- [ ] @lucksus 
- [ ] @artbrock

**Comment by christopherreay** [comment]
So we have taken a step back from this.

zippy has picked out go-libp2p-kbucket as a component we can pluck from go-libp2p-kad-dht, to produce the best effort/reuse ratio.

We are currently exploring in more detail the comparison between holochain/action.go and its associated code, and go-libp2p-kad-dht and its afilliated code, to see what the cross over is.

**Comment by zippy** [comment]
obsolete

**Comment by zippy** [comment]
obsolete
