### ISSUE TITLE
scripts/process for keeping dockerfile up to date

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-proto#322]
- [ ] make a script inside the docker container that self-updates, or rebuilds the docker image

**Comment by zippy** [comment]
We also need to update the documentation (docker/README.md) and docker/hc-dev-tools scripts.

**Comment by philipbeadle** [comment]
I'll update the Dockerfile so it builds and publishes to Docker Hub

**Comment by philipbeadle** [comment]
New travis file and Dockerfile will now build a Docker image and publish it to Docker Hub when Master branch is updated.
