### ISSUE TITLE
sample app tests broken

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-proto#371]
- [ ] holochat
- [x] cointoss
- [x] clutter
- [ ] dpki
- [ ] holodex

**Comment by zippy** [comment]
as of 766a868b5 `test.examples` yields:

```
Test results:
holochat  exit code: 0
clutter  exit code: 2
cointoss  exit code: 0
holodex  exit code: 2
dpki  exit code: 2
```

**Comment by zippy** [comment]
also run all scenario tests too...

**Comment by zippy** [comment]
See also #224

**Comment by zippy** [comment]
Hey @philipbeadle lets talk about if we really want to fix this script, or if you want to integrate sample app testing for releases in some other way, in which case we close this ticket.

**Comment by philipbeadle** [comment]
Yesterday we got clutter to run its hcdev tests as part of the build.  You can see the outputs in thsi build https://travis-ci.org/Holochain/clutter/builds/349711247.  We use the docker image and then run the tests inside it :) . We can do this for all of the apps

**Comment by zippy** [comment]
I updated this script to be able to pull from any branch.  So for example running now like this producdes :

```
$ bin/test.examples -b=develop
...
Test results:
HoloWorld  exit code: 0
fractal-wiki  exit code: 0
clutter  exit code: 0
cointoss  exit code: 0
```

**Comment by zippy** [comment]
The thing I like about this script is that it allows us to test all of the sample apps at once before a release.  Theoretically people should be keeping the `develop` branch of each app up-to-date with the `develop` of holochain, but this doesn't happen, and this kind of the script really helps to see when there's problem.
