### ISSUE TITLE
Add JSON dump option to hcdev

### ISSUE THREAD

**Issue by philipbeadle** [holochain/holochain-proto#570]
hcdev allows dumping data as well. Please add this option to hcdev.

**Comment by artbrock** [comment]
Ideally... when hcdev test is run with --dump...   show the dump the chain after the tests so that we can inspect what got created.

**Comment by clarenceb** [comment]
I have submitted a PR for this issue: https://github.com/Holochain/holochain-proto/pull/586 but the Travis CI build keeps failing on `docker login` before pushing the docker image.  See that Pr for more details and log output.  I'm not sure why that is happening.  Perhaps reset the docker hub username/password variables?
