### ISSUE TITLE
Docker image for develop branch builds from source code on master branch

### ISSUE THREAD

**Issue by clarenceb** [Holochain/holochain-proto#589]
I believe the Docker build for the `develop`  branch is not implemented correctly since the `Dockerfile` uses `RUN go get -d -v github.com/Holochain/holochain-proto` to fetch the source code.  In Go, `go get ...` fetches code from the `master` branch.  This means that the Docker image tagged `metacurrency/holochain:develop` actually uses code from the wrong branch.

**Comment by philipbeadle** [comment]
Nice catch, need to do a git checkout develop and then build it.

**Comment by philipbeadle** [comment]
Merged.
