### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by 8jef** [Holochain/holochain-proto#590]
OS Mint 18.3  x64 French language
GO 1.10

The make process stops here:

[get ] [install] go-libp2p                     QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdW
[done] [install] go-libp2p                     QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdW
go get . cWDL 0s
make: go: Command not found
Makefile:43: recipe for target 'all' failed
make: *** [all] Error 127

Any help? Thanks in advance
Cheers!

**Comment by Connoropolous** [comment]
Seems that even though you have 'go' installed, it isn't a command that is available in your terminal...

If you just type `go version` into a terminal, does it list the go version?

**Comment by 8jef** [comment]
You are right, I had to source /etc/profile again.

Then the error stays. Here it is, starting from the same point:

[get ] [install] go-libp2p QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdW
[done] [install] go-libp2p  QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdW
go get . cWDL 0s
# github.com/metacurrency/holochain
./gossip.go:249:29: cannot use glist[i] (type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID) as type "github.com/libp2p/go-libp2p-peer".ID in argument to "github.com/Holochain/holochain-proto/hash".HashFromPeerID
./gossip.go:252:29: cannot use dht.h.nodeID (type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID) as type "github.com/libp2p/go-libp2p-peer".ID in argument to "github.com/Holochain/holochain-proto/hash".HashFromPeerID
./gossip.go:257:13: cannot use "github.com/Holochain/holochain-proto/hash".PeerIDFromHash(hlist[i]) (type "github.com/libp2p/go-libp2p-peer".ID) as type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID in assignment
./kad_query.go:191:30: cannot use next (type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID) as type "github.com/libp2p/go-libp2p-peer".ID in send
./kad_query.go:216:17: cannot use p (type "github.com/libp2p/go-libp2p-peer".ID) as type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID in argument to r.queryPeer
./kad_rpc.go:122:26: cannot use id (type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID) as type "github.com/libp2p/go-libp2p-peer".ID in argument to "github.com/Holochain/holochain-proto/hash".HashFromPeerID
./kad_rpc.go:195:28: cannot use node.HashAddr (type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID) as type "github.com/libp2p/go-libp2p-peer".ID in argument to "github.com/Holochain/holochain-proto/hash".HashFromPeerID
./kad_table.go:144:40: cannot use id (type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID) as type "github.com/libp2p/go-libp2p-peer".ID in argument to "github.com/Holochain/holochain-proto/hash".HashFromPeerID
./kad_table.go:163:26: cannot use target (type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID) as type "github.com/libp2p/go-libp2p-peer".ID in argument to "github.com/Holochain/holochain-proto/hash".HashFromPeerID
./kad_table.go:165:30: cannot use e.Value.("gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID) (type "gx/ipfs/QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB/go-libp2p-peer".ID) as type "github.com/libp2p/go-libp2p-peer".ID in argument to "github.com/Holochain/holochain-proto/hash".HashFromPeerID
./kad_table.go:165:30: too many errors
Makefile:43: recipe for target 'all' failed
make: *** [all] Error 2

--------------------
googling it sends me here: https://www.meetup.com/fr-FR/Bay-Area-Holochain-Meetup/events/247757217/?eventId=247757217

Look at last comment down the page. Same difference.
Cheers!

**Comment by 8jef** [comment]
and I'm running go v1.10
Thanks

**Comment by Connoropolous** [comment]
Hmm, I just hit something similar...
This seems to have to do with the repository having moved recently.

It may be worthwhile to remove the /github.com/metacurrency/holochain directory locally, and run the new commands instead. I think this was an unintended consequence of the repo move

```
go get -d -v github.com/Holochain/holochain-proto
cd $GOPATH/src/github.com/Holochain/holochain-proto
make
```

**Comment by 8jef** [comment]
Looks better! Thank you very mucho :)
Make done!

**Comment by Connoropolous** [comment]
Rad

**Comment by zippy** [comment]
yes this probably would have worked from the develop branch... where all that stuff is fixed.

**Comment by crytoHODLER** [comment]
Unable to install holochain, please help !!

[done] [install] 0s    QmNhVCV7kgAqW6oh6n8m9myxT2ksGPhVZnHkzkBvR5qg2d go-multico[done] [install] 0s    Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ go-text
[get ] [install]       QmcLqWSFsaQ8Ujh8Ys8i9JPHVy1CcdPoqV23M9S3ufdVbn go-sockadd[done] [install] 0s    QmcLqWSFsaQ8Ujh8Ys8i9JPHVy1CcdPoqV23M9S3ufdVbn go-sockadd[get ] [install]       Qma73Sqt13DzHzveZ667BBfraM7MuMrPepUXjmv812JhRS go-net-res[done] [install] 0s    Qma73Sqt13DzHzveZ667BBfraM7MuMrPepUXjmv812JhRS go-net-res[done] [install] 0s    QmSGRM5Udmy1jsFBr1Cawez7Lt7LZ3ZKA23GGVEsiEW6F3 eventfd
[done] [install] 0s    QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts websocket
[get ] [install]       QmafgXF3u3QSWErQoZ2URmQp5PFG384htoE7J338nS2H7T go-multiba[done] [install] 0s    QmafgXF3u3QSWErQoZ2URmQp5PFG384htoE7J338nS2H7T go-multiba[done] [install] 1ms   QmWjNfGgm61ABELTxPDwvNDm18j1EmQiPt9zXkCSEYgMDm spdystream
[done] [install] 0s    QmQtBcHtRy9BxjawZjWJBn8aSKbqraBnQiVsc3wt9w9TTn goupnp
[done] [install] 0s    Qmf2fBLzCvFxs3vvZaoQyKSTv2rjApek4F1kzRxAfK6P4P gateway
[done] [install] 0s    QmYsYNh6saxUYHajdj49uiRzdxQgiFTtymrjf3d1f2Cer4 go-nat-pmp
[done] [install] 0s    QmeFPvhFJGXGiXAc9zunNxZjCaWgYQpcsdwip2NWLcccyw GoEndian
[done] [install] 0s    QmfVj3x4D6Jkq9SEoi5n2NmoUomLwoeiwnYz2KQa15wRw6 base32
go get . 8] 0s
go get ./ui 
go get ./apptest 
go get ./cmd/ 
go get ./cmd/bs/ 
# github.com/holochain/holochain-proto/cmd/bs
gx/ipfs/QmaPHkZLbQQbvcyavn8q1GFHg6o6yeceyHFSJ3Pjf3p3TQ/go-crypto/blake2b.supportAVX2: relocation target runtime.support_avx2 not defined
make: *** [all] Error 2
Dangs-MacBook-Pro:holochain-proto dangphiong$ 

thanks for helping me
