### ISSUE TITLE
HolochainError: routing: not found

### ISSUE THREAD

**Issue by philipbeadle** [Holochain/holochain-proto#593]
Scenario testing intermittently fails with HolochainError: routing: not found.  This also happens in the docker containers and is a recent issue.

tried with mdns, bootstrap etc, seems to be a low level issue as this error does not appear in our code.

**Comment by philipbeadle** [comment]
In the Clutter branhc 48-anchors run 
```
  hcdev -mdns=true scenario collisionOfHandles
```

**Comment by zippy** [comment]
ok, the "routing: not found" error is really exactly the same as the "hash not found" error.  So I've unified them in https://github.com/Holochain/holochain-proto/tree/593-routing-not-found-err

There may still be other stuff going on that needs fixing here...

**Comment by artbrock** [comment]
I would suggest modification of the Error text to be "No peers in DHT routing table found with requested hash."  Or something along those lines... rather than just "No peers in DHT routing table."

**Comment by zippy** [comment]
The message `DHT Query with no peers in routing table!` happens only when there really aren't any peers in the table.  The message `routing: not found` has been removed from as it really was the same as HashNotFound.
