### ISSUE TITLE
get(hash) return undefined

### ISSUE THREAD

**Issue by philipbeadle** [Holochain/holochain-proto#595]
Please make it so that get(hash) returns undefined if it cannot be found instead of an error.

**Comment by zippy** [comment]
Thinking this through even more, I think I'm going to add a constant:  HC.NullHash which you can use for the comparison, instead of undefined because this would allow us to use, for example the empty string, or what ever makes sense.

**Comment by zippy** [comment]
The deeper issue here is that we are saying that this case is not an error case, so we don't throw or return a standard Holochain Error object.  Instead we return some testable value.

So the question for me is should we have a defined constant to test against that works across all languages not just javascript undefined.  For now I'm building it to be HC.GetError.HashNotFound   But I don't really like that.

Something to consider is that `get()` returns different types of things depending on what you put into the getmask.  So if part of the purpose of this is to simplify a switch on the return value, that may not help in all cases.  

Another part of the  issue is that if you do an `update()` or` delete()` on a hash that doesn't exist, in those cases it IS an error condition.  So it should throw an error or return the usual error object.  But then will this throw devs off who might also expect to get the same kind of result?
