### ISSUE TITLE
Add a flag to create separate instance of app in hcdev

### ISSUE THREAD

**Issue by philipbeadle** [Holochain/holochain-proto#608]
I'd really like to be able to run multiple instances of an app without having to copy the dna into folders and run from the folder.  Something like
```
  hcdev -no-nat-upnp -port=6002 -agentID=agent4141 -mdns=true -instance=clutter3141 web 4141
```

which would run from the clutter folder and create a /Users/philipbeadle/.holochaindev/clutter3141 folder

:)

**Comment by zippy** [comment]
You can already do this, sort of, with the execpath flag:

`HCLOG_DHT_ENABLE=1 hcdev -execpath=~./holochaindev2 -no-nat-upnp -port=6002 -agentID=notLucy -mdns=true web 3142`

the execpath flag creates an entirely different path in which to store the instance data.

**Comment by philipbeadle** [comment]
Awesome :) Ill try that

**Comment by philipbeadle** [comment]
Works perfectly :)
