### ISSUE TITLE
make error on Mac

### ISSUE THREAD

**Issue by jeremyboom8** [holochain/holochain-proto#636]
Followed http://developer.holochain.org/Install_Holochain and at the last step: $ make
Error:

gx-go get github.com/holochain/holochain-proto
make: gx-go: No such file or directory
make: *** [deps] Error 1

**Comment by zippy** [comment]
try checking out the `develop` branch.  Does it still happen there?

**Comment by jeremyboom8** [comment]
I had missed a part of the instructions.

**Comment by Connoropolous** [comment]
@jeremyboom8 someone else just hit this issue lol. Do you remember what step you accidentally skipped?

**Comment by jeremyboom8** [comment]
I think I had missed this step, or applied it in the wrong place. I can't remember exactly though!

Step 4. in your editor, add the following to .bash_profile, and save it

export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
