### ISSUE TITLE
Add an Index to the Dump function

### ISSUE THREAD

**Issue by philipbeadle** [holochain/holochain-proto#643]
I'd like to be able to set an index when doing 
```
  hcadmin dump clutter --chain --index=4
```
so that I can just get the latest entries for the dump function.

**Comment by clarenceb** [comment]
@zippy This also needs to be added to the `dot` dump too :|

It would be good to separate the output formatters from the chain traversal so that this only needs to exist in one place (easier said than done).  That's probably some refactoring and tech debt cleanup.
