### ISSUE TITLE
Cannot run shell scripts on NixOS

### ISSUE THREAD

**Issue by gmarmstrong** [holochain/holochain-proto#649]
None of the executable files with the shebang `#!/bin/bash` will run on NixOS because `/bin/bash` does not exist. While this is more precise on some systems, it is not portable to others. The standard practice is to only use the absolute paths that exist on every Unix system: `/bin/sh` and `/usr/bin/env`.

Specifically, `#!/bin/sh` should be left alone, but each `#!/bin/bash` should be changed to `/usr/bin/env bash`. I'm making this change right now.

See also: https://unix.stackexchange.com/a/77586/191530

**Comment by zippy** [comment]
Hey @philipbeadle and @lucksus care to comment on this?  Seems pretty reasonable, but I want to make sure that it won't have any effect on the Docker setup.
