### ISSUE TITLE
running 'make' throws an error on windows

### ISSUE THREAD

**Issue by samwa** [holochain/holochain-proto#659]
Following the instructions here: https://developer.holochain.org/Install_Holochain
running 'make' from %GOPATH%\go\src\github.com\Holochain\holochain-proto
I get the following error

process_begin: CreateProcess(NULL, gx-go get github.com/Holochain/holochain-proto, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [deps] Error 2

this is on Windows 10 Enterprise

**Comment by Connoropolous** [comment]
Hi @samwa ... what I am curious about is how did you end up with "Holochain/holochain-proto"? 

I think what you want is "holochain/holochain-proto". "Holochain" was previously the name of the org on github, but we changed it to lowercase. This sometimes breaks the build. Try retracing the steps, but with a lowercase :)

**Comment by samwa** [comment]
Thanks, i've tried this with the latest instructions on a newly built machine and it works fine
