### ISSUE TITLE
fix bridging naming convention

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-proto#661]
From & To not so good, maybe caller/callee (as in the code) or (client/provider)...

**Comment by gcassel** [comment]
Hi zippy, I guess you desire a name which is a noun?  I'd probably recommend *sender/receiver*, per my extremely generic definitions for [send](https://github.com/gcassel/Modular-Organization-Terminology/blob/master/terms/send.md) and [receive](https://github.com/gcassel/Modular-Organization-Terminology/blob/master/terms/receive.md).   However I suppose that many approaches would work.

**Comment by zippy** [comment]
Well, both sides are sending and receiving.  The real issue is who is the initiator, hence the "caller/callee" idea.  Currently the bridgeSpecs have "From/To" which is crazy confusing. :-P

**Comment by gcassel** [comment]
Okay maybe I should've looked at the code before commenting.   I see where English is challenging here, and caller/callee looks serviceable!
