### ISSUE TITLE
validateLink function not included in sampleZome.js generated by hcdev init

### ISSUE THREAD

**Issue by willemolding** [holochain/holochain-proto#738]
I'm not sure if this omission is intentional or not. On the documentation page this is listed as a required callback but dApps appear to work fine without it. The only issue is that committing link entries fails silently making it difficult to identify the source of the problem.

I propose that a template validateLink function should be included that returns true by default. Documentation should be included in a docstring similar to the other required callbacks.

**Comment by willemolding** [comment]
Closing as issue is closely related to #745

**Comment by thedavidmeister** [comment]
@willemolding i got burned by the same thing last week and lost waaay too much time on something this dumb, lol

**Comment by thedavidmeister** [comment]
i agree that it either has to be a hard requirement, or validate by default, silent fails are not OK :P
