### ISSUE TITLE
HC.HashNotFound undefined

### ISSUE THREAD

**Issue by jdeepee** [holochain/holochain-proto#742]
Currently developing an application on Holochain, when It try to use the global variable HashNotFound I find that it is undefined, is this a result of an undocumented API change or is there a bug?

**Comment by zippy** [comment]
It has been implemented.  Perhaps you need to update your holochain version?  when you do `hcdev -v` what do you see for the holochain version?

**Comment by jdeepee** [comment]
hcdev version 0.0.3 (holochain 19)

**Comment by zippy** [comment]
Yep, quite old.  You need to update to latest master (hc 25) or develop.
