### ISSUE TITLE
priv.key file exposed

### ISSUE THREAD

**Issue by ko-redtruck** [holochain/holochain-proto#756]
I accidentally uploaded my priv.key file to GitHub. What can happen if somebody has this file?

**Comment by pdaoust** [comment]
@ko-redtruck it does mean someone can impersonate you. Nice thing about this is that it's cheap to create a new identity, so I'd just throw out that priv.key and run `hcadmin init <your-agent-string>` again.

**Comment by alanz** [comment]
For cleanup purposes (closing the stable door), you can look at https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by ko-redtruck** [comment]
@pdaoust @alanz Thanks for the clarification!
