### ISSUE TITLE
Holochain-proto missing from docker store

### ISSUE THREAD

**Issue by SimunKaracic** [holochain/holochain-proto#768]
I appears to have been replaced with the Rust version.

Should I just give up on the Go version? Because the Go based install does not work on Windows (instances of the same app cannot find eachother on Windows). 

Just trying to see what my options for developing new Holochain apps on Windows are.

**Comment by zippy** [comment]
Hey there @SimunKaracic , thanks for reporting the issue, we just had a snafu with our dockerhub account.  I just re-added the holochain-proto repo to it and working on rebuilding the docker image, I'll ping you when it's up.

**Comment by SimunKaracic** [comment]
You're almost there, it's back on docker store. However, there appear to be no tags, so I can't pull. Can You please put a tag up there, so I can try again?

**Comment by mikeyb** [comment]
Please tag docker release :)  Can't play with holochain and I need to check it out for business requirements
