### ISSUE TITLE
Filename misspelled in the Ubuntu release

### ISSUE THREAD

**Issue by pendashteh** [holochain/holochain-proto#772]
"ubuntu" is spelled as "ubunutu" in the file name: holochain-alpha-26-ubunutu

When you download the ZIP file for the ubuntu release for "Alpha 0.1.0 (26) -- Developer Preview(2018-07-10)".

Release link: https://github.com/holochain/holochain-proto/releases/tag/v0.1.0-alpha-26

Zip file: https://github.com/holochain/holochain-proto/releases/download/v0.1.0-alpha-26/holochain-alpha-26-ubuntu.zip

(Also it would be good to delete __MACOSX folder from the ZIP file content).

**Comment by pendashteh** [comment]
Can somebody assign this to @willemolding?

**Comment by willemolding** [comment]
Should be all good now
